### ISSUE TITLE
question about the wave velocity in this system

### ISSUE THREAD

**Issue by ZoudaLevy** [fancompute/wavetorch#8]
Just saw the paper in Science Advances. Really fantastic work!!
What is the wave velocity with respect to the mesh size and the time step? I guess the device is 3D-printable.

**Comment by ianwilliamson** [comment]
Thanks for your interest in the work!

In the paper we use a "normalized" wave speed. I suppose you could translate this into units of dx/dt if you wanted, but I'm not sure how useful it is to do that since our choice of dx and dt are somewhat arbitrary. We chose the _relative_ wave speeds in the two materials to approximate those of air and polymer (see the citation). The simulation shown in the paper is really a proof of principle to demonstrate the physical dynamics of the wave RNN. Note also that the simulation in the paper is 2D, which also means that it would be challenging to 3D print a working version of that _exact_ design shown in the figure.

In general, the constraint in these types of simulations is that dx, dy, and dt satisfy the [CFL stability condition](https://en.wikipedia.org/wiki/Courant%E2%80%93Friedrichs%E2%80%93Lewy_condition). You could also train a model using exact wave speeds for the materials, e.g. `c = 331.0` m/s in air, while picking suitable values for dx and dt. We've previously done this in wavetorch and it works fine.
